<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto

namespace Proto_app;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto_app.GetAhorizedMenusByAppIdAndUserIdRequest</code>
 */
class GetAhorizedMenusByAppIdAndUserIdRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 AppId = 1;</code>
     */
    protected $AppId = 0;
    /**
     * Generated from protobuf field <code>int64 UserId = 2;</code>
     */
    protected $UserId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $AppId
     *     @type int|string $UserId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 AppId = 1;</code>
     * @return int|string
     */
    public function getAppId()
    {
        return $this->AppId;
    }

    /**
     * Generated from protobuf field <code>int64 AppId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkInt64($var);
        $this->AppId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 UserId = 2;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->UserId;
    }

    /**
     * Generated from protobuf field <code>int64 UserId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->UserId = $var;

        return $this;
    }

}

