<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission.proto

namespace GPBMetadata;

class Permission
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Struct::initOnce();
        $pool->internalAddGeneratedFile(
            '
 6
permission.protoproto_permission"$
GetRoleUserByIdRequest

Id ("B
GetRoleUserByIdResponse\'
Result (2.google.protobuf.Struct"-
GetRoleUsersByUserIdRequest
UserId ("G
GetRoleUsersByUserIdResponse\'
Result (2.google.protobuf.Struct"D
#GetRoleUsersByAppIdAndUserIdRequest
AppId (
UserId ("O
$GetRoleUsersByAppIdAndUserIdResponse\'
Result (2.google.protobuf.Struct" 
GetRoleByIdRequest

Id (">
GetRoleByIdResponse\'
Result (2.google.protobuf.Struct""
GetActionByIdRequest

Id ("@
GetActionByIdResponse\'
Result (2.google.protobuf.Struct"\'
GetPermissionsByIdRequest

Id ("E
GetPermissionsByIdResponse\'
Result (2.google.protobuf.Struct"F
%GetPermissionsByAppIdAndRoleIdRequest
AppId (
RoleId ("Q
&GetPermissionsByAppIdAndRoleIdResponse\'
Result (2.google.protobuf.Struct"H
&GetPermissionsByAppIdAndRoleIdsRequest
AppId (
RoleIds ("R
\'GetPermissionsByAppIdAndRoleIdsResponse\'
Result (2.google.protobuf.Struct"c
0GetPermissionsByAppIdAndRoleIdAndActionIdRequest
AppId (
RoleId (
ActionId ("\\
1GetPermissionsByAppIdAndRoleIdAndActionIdResponse\'
Result (2.google.protobuf.Struct"e
1GetPermissionsByAppIdAndRoleIdAndActionIdsRequest
AppId (
RoleId (
	ActionIds ("]
2GetPermissionsByAppIdAndRoleIdAndActionIdsResponse\'
Result (2.google.protobuf.Struct"e
1GetPermissionsByAppIdAndRoleIdsAndActionIdRequest
AppId (
RoleIds (
ActionId ("]
2GetPermissionsByAppIdAndRoleIdsAndActionIdResponse\'
Result (2.google.protobuf.Struct"g
2GetPermissionsByAppIdAndRoleIdsAndActionIdsRequest
AppId (
RoleIds (
	ActionIds ("^
3GetPermissionsByAppIdAndRoleIdsAndActionIdsResponse\'
Result (2.google.protobuf.Struct"g
2GetPermissionsByAppIdAndRoleIdAndObjectTypeRequest
AppId (
RoleId (

ObjectType (	"^
3GetPermissionsByAppIdAndRoleIdAndObjectTypeResponse\'
Result (2.google.protobuf.Struct"i
3GetPermissionsByAppIdAndRoleIdAndObjectTypesRequest
AppId (
RoleId (
ObjectTypes (	"_
4GetPermissionsByAppIdAndRoleIdAndObjectTypesResponse\'
Result (2.google.protobuf.Struct"i
3GetPermissionsByAppIdAndRoleIdsAndObjectTypeRequest
AppId (
RoleIds (

ObjectType (	"_
4GetPermissionsByAppIdAndRoleIdsAndObjectTypeResponse\'
Result (2.google.protobuf.Struct"k
4GetPermissionsByAppIdAndRoleIdsAndObjectTypesRequest
AppId (
RoleIds (
ObjectTypes (	"`
5GetPermissionsByAppIdAndRoleIdsAndObjectTypesResponse\'
Result (2.google.protobuf.Struct"Ñ
=GetPermissionsByAppIdAndRoleIdAndActionIdAndObjectTypeRequest
AppId (
RoleId (
ActionId (

ObjectType (	"i
>GetPermissionsByAppIdAndRoleIdAndActionIdAndObjectTypeResponse\'
Result (2.google.protobuf.Struct"Ü
>GetPermissionsByAppIdAndRoleIdsAndActionIdAndObjectTypeRequest
AppId (
RoleIds (
ActionId (

ObjectType (	"j
?GetPermissionsByAppIdAndRoleIdsAndActionIdAndObjectTypeResponse\'
Result (2.google.protobuf.Struct"à
?GetPermissionsByAppIdAndRoleIdsAndActionIdsAndObjectTypeRequest
AppId (
RoleIds (
	ActionIds (

ObjectType (	"k
@GetPermissionsByAppIdAndRoleIdsAndActionIdsAndObjectTypeResponse\'
Result (2.google.protobuf.Struct"ä
@GetPermissionsByAppIdAndRoleIdsAndActionIdsAndObjectTypesRequest
AppId (
RoleIds (
	ActionIds (
ObjectTypes (	"l
AGetPermissionsByAppIdAndRoleIdsAndActionIdsAndObjectTypesResponse\'
Result (2.google.protobuf.Struct2„

PermissionZ
GetRoleById$.proto_permission.GetRoleByIdRequest%.proto_permission.GetRoleByIdResponseu
GetRoleUsersByUserId-.proto_permission.GetRoleUsersByUserIdRequest..proto_permission.GetRoleUsersByUserIdResponseç
GetRoleUsersByAppIdAndUserId5.proto_permission.GetRoleUsersByAppIdAndUserIdRequest6.proto_permission.GetRoleUsersByAppIdAndUserIdResponse`
GetActionById&.proto_permission.GetActionByIdRequest\'.proto_permission.GetActionByIdResponseo
GetPermissionsById+.proto_permission.GetPermissionsByIdRequest,.proto_permission.GetPermissionsByIdResponseì
GetPermissionsByAppIdAndRoleId7.proto_permission.GetPermissionsByAppIdAndRoleIdRequest8.proto_permission.GetPermissionsByAppIdAndRoleIdResponseñ
GetPermissionsByAppIdAndRoleIds8.proto_permission.GetPermissionsByAppIdAndRoleIdsRequest9.proto_permission.GetPermissionsByAppIdAndRoleIdsResponse¥
)GetPermissionsByAppIdAndRoleIdAndActionIdB.proto_permission.GetPermissionsByAppIdAndRoleIdAndActionIdRequestC.proto_permission.GetPermissionsByAppIdAndRoleIdAndActionIdResponse∑
*GetPermissionsByAppIdAndRoleIdAndActionIdsC.proto_permission.GetPermissionsByAppIdAndRoleIdAndActionIdsRequestD.proto_permission.GetPermissionsByAppIdAndRoleIdAndActionIdsResponse∑
*GetPermissionsByAppIdAndRoleIdsAndActionIdC.proto_permission.GetPermissionsByAppIdAndRoleIdsAndActionIdRequestD.proto_permission.GetPermissionsByAppIdAndRoleIdsAndActionIdResponse∫
+GetPermissionsByAppIdAndRoleIdsAndActionIdsD.proto_permission.GetPermissionsByAppIdAndRoleIdsAndActionIdsRequestE.proto_permission.GetPermissionsByAppIdAndRoleIdsAndActionIdsResponse∫
+GetPermissionsByAppIdAndRoleIdAndObjectTypeD.proto_permission.GetPermissionsByAppIdAndRoleIdAndObjectTypeRequestE.proto_permission.GetPermissionsByAppIdAndRoleIdAndObjectTypeResponseΩ
,GetPermissionsByAppIdAndRoleIdAndObjectTypesE.proto_permission.GetPermissionsByAppIdAndRoleIdAndObjectTypesRequestF.proto_permission.GetPermissionsByAppIdAndRoleIdAndObjectTypesResponseΩ
,GetPermissionsByAppIdAndRoleIdsAndObjectTypeE.proto_permission.GetPermissionsByAppIdAndRoleIdsAndObjectTypeRequestF.proto_permission.GetPermissionsByAppIdAndRoleIdsAndObjectTypeResponse¿
-GetPermissionsByAppIdAndRoleIdsAndObjectTypesF.proto_permission.GetPermissionsByAppIdAndRoleIdsAndObjectTypesRequestG.proto_permission.GetPermissionsByAppIdAndRoleIdsAndObjectTypesResponse€
6GetPermissionsByAppIdAndRoleIdAndActionIdAndObjectTypeO.proto_permission.GetPermissionsByAppIdAndRoleIdAndActionIdAndObjectTypeRequestP.proto_permission.GetPermissionsByAppIdAndRoleIdAndActionIdAndObjectTypeResponseﬁ
7GetPermissionsByAppIdAndRoleIdsAndActionIdAndObjectTypeP.proto_permission.GetPermissionsByAppIdAndRoleIdsAndActionIdAndObjectTypeRequestQ.proto_permission.GetPermissionsByAppIdAndRoleIdsAndActionIdAndObjectTypeResponse·
8GetPermissionsByAppIdAndRoleIdsAndActionIdsAndObjectTypeQ.proto_permission.GetPermissionsByAppIdAndRoleIdsAndActionIdsAndObjectTypeRequestR.proto_permission.GetPermissionsByAppIdAndRoleIdsAndActionIdsAndObjectTypeResponse‰
9GetPermissionsByAppIdAndRoleIdsAndActionIdsAndObjectTypesR.proto_permission.GetPermissionsByAppIdAndRoleIdsAndActionIdsAndObjectTypesRequestS.proto_permission.GetPermissionsByAppIdAndRoleIdsAndActionIdsAndObjectTypesResponseB*Z(sv-mgrsys-auth/core/permission/rpc/protobproto3'
        , true);

        static::$is_initialized = true;
    }
}

