<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto

namespace GPBMetadata;

class App
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Struct::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ð
	app.proto	proto_app"
GetAppByIdRequest

Id ("=
GetAppByIdResponse\'
Result (2.google.protobuf.Struct2P
AppI

GetAppById.proto_app.GetAppByIdRequest.proto_app.GetAppByIdResponsebproto3'
        , true);

        static::$is_initialized = true;
    }
}

