<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto

namespace GPBMetadata;

class App
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Struct::initOnce();
        $pool->internalAddGeneratedFile(
            '
þ
	app.proto	proto_app"
GetAppByIdRequest

Id ("=
GetAppByIdResponse\'
Result (2.google.protobuf.Struct"H
\'GetAhorizedMenusByAppIdAndUserIdRequest
AppId (
UserId ("S
(GetAhorizedMenusByAppIdAndUserIdResponse\'
Result (2.google.protobuf.Struct2Þ
AppI

GetAppById.proto_app.GetAppByIdRequest.proto_app.GetAppByIdResponse‹
 GetAhorizedMenusByAppIdAndUserId2.proto_app.GetAhorizedMenusByAppIdAndUserIdRequest3.proto_app.GetAhorizedMenusByAppIdAndUserIdResponsebproto3'
        , true);

        static::$is_initialized = true;
    }
}

