<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission.proto

namespace Proto_permission;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto_permission.GetPermissionsByAppIdAndRoleIdAndObjectTypesResponse</code>
 */
class GetPermissionsByAppIdAndRoleIdAndObjectTypesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct Result = 1;</code>
     */
    protected $Result = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Struct $Result
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Permission::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct Result = 1;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getResult()
    {
        return $this->Result;
    }

    public function hasResult()
    {
        return isset($this->Result);
    }

    public function clearResult()
    {
        unset($this->Result);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct Result = 1;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->Result = $var;

        return $this;
    }

}

