<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission.proto

namespace Proto_permission;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto_permission.GetPermissionsByAppIdAndRoleIdsAndActionIdAndObjectTypeRequest</code>
 */
class GetPermissionsByAppIdAndRoleIdsAndActionIdAndObjectTypeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 AppId = 1;</code>
     */
    protected $AppId = 0;
    /**
     * Generated from protobuf field <code>repeated int64 RoleIds = 2;</code>
     */
    private $RoleIds;
    /**
     * Generated from protobuf field <code>int64 ActionId = 3;</code>
     */
    protected $ActionId = 0;
    /**
     * Generated from protobuf field <code>string ObjectType = 4;</code>
     */
    protected $ObjectType = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $AppId
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $RoleIds
     *     @type int|string $ActionId
     *     @type string $ObjectType
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Permission::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 AppId = 1;</code>
     * @return int|string
     */
    public function getAppId()
    {
        return $this->AppId;
    }

    /**
     * Generated from protobuf field <code>int64 AppId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkInt64($var);
        $this->AppId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 RoleIds = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRoleIds()
    {
        return $this->RoleIds;
    }

    /**
     * Generated from protobuf field <code>repeated int64 RoleIds = 2;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRoleIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->RoleIds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 ActionId = 3;</code>
     * @return int|string
     */
    public function getActionId()
    {
        return $this->ActionId;
    }

    /**
     * Generated from protobuf field <code>int64 ActionId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setActionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ActionId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ObjectType = 4;</code>
     * @return string
     */
    public function getObjectType()
    {
        return $this->ObjectType;
    }

    /**
     * Generated from protobuf field <code>string ObjectType = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setObjectType($var)
    {
        GPBUtil::checkString($var, True);
        $this->ObjectType = $var;

        return $this;
    }

}

