<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission.proto

namespace Proto_permission;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto_permission.GetRoleUsersByUserIdRequest</code>
 */
class GetRoleUsersByUserIdRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 UserId = 1;</code>
     */
    protected $UserId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $UserId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Permission::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 UserId = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->UserId;
    }

    /**
     * Generated from protobuf field <code>int64 UserId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->UserId = $var;

        return $this;
    }

}

